package de.marcelhuber.fitnessstudiogui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import javax.swing.Timer;
//import javax.swing.table.*;
import de.marcelhuber.datenbank.*;

/**
 *
 * @author Huber, Marcel
 */
public class JFrameFitnessStudioVerwaltung extends javax.swing.JFrame {

    private Map<Integer, List<String>> standardMitgliederMap;
    private MyStandardMitgliederListModel msmlm;
    private MyTableModel mtm;
    FitnessStudio fitnessstudio = new FitnessStudio("Huber-Fitness",
            "54294 Trier", 2017);
    private String dummyNachname;
    private String dummyVorname;
    private String dummyPlz;
    private String dummyWohnort;
    private String dummyGeburtstagsString;
    private int dummyTagDerGeburt, dummyMonatDerGeburt, dummyJahrDerGeburt;
    private int dummyAlter;
    private boolean mitgliedErzeugbar;
    private List<JTextField> jTextfeldListe = new ArrayList<>();

    /* eigentlich wäre ein Array
     angebrachter, aber ArrayList zum Testen */
    /**
     * Creates new form JFrameFitnessStudioVerwaltung
     */
    public JFrameFitnessStudioVerwaltung() {
        msmlm = new MyStandardMitgliederListModel();
        mtm = new MyTableModel();
        initComponents();
        setLocationRelativeTo(null);
        System.out.println(mtm.getColumnClass(2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogFehlerhafteIDEingabe = new javax.swing.JDialog();
        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDemoAufKonsole = new javax.swing.JPanel();
        jLabelHauptprogramm = new javax.swing.JLabel();
        jButtonStartHauptprogramm = new javax.swing.JButton();
        textMethodenNummer = new javax.swing.JTextField();
        jPanelMitglieder_Listenausgabe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMitglieder = new javax.swing.JList<String>();
        jPanelMitglieder_Tabelle = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMitglieder = new javax.swing.JTable();
        jPanelStd_MitgliederVerwalten = new javax.swing.JPanel();
        jLabelMitgliedsdatenUeberschrift = new javax.swing.JLabel();
        jLabelNachName = new javax.swing.JLabel();
        jLabelVorname = new javax.swing.JLabel();
        jLabelPlz = new javax.swing.JLabel();
        jLabelWohnort = new javax.swing.JLabel();
        jLabelMitgliedsnummer = new javax.swing.JLabel();
        jTextNachname = new javax.swing.JTextField();
        jTextVorname = new javax.swing.JTextField();
        jTextPlz = new javax.swing.JTextField();
        jTextWohnort = new javax.swing.JTextField();
        jLabelErrechneteMitgliedsnummer = new javax.swing.JLabel();
        jButtonMitgliedVorbereiten = new javax.swing.JButton();
        jLabelAlter = new javax.swing.JLabel();
        jTextAlter = new javax.swing.JTextField();
        jTextErrechneteMitgliedsnummer = new javax.swing.JTextField();
        jButtonMitgliedsdatenSpeichern = new javax.swing.JButton();
        jTextNachnameVorschau = new javax.swing.JTextField();
        jTextVornameVorschau = new javax.swing.JTextField();
        jTextPlzVorschau = new javax.swing.JTextField();
        jTextWohnortVorschau = new javax.swing.JTextField();
        jTextAlterVorschau = new javax.swing.JTextField();
        jLabelMitgliedsdatenUeberschrift1 = new javax.swing.JLabel();
        jButtonDelete_ID = new javax.swing.JButton();
        jTextDelete_ID = new javax.swing.JTextField();
        jButtonMitgliedEditierbar = new javax.swing.JButton();
        jFormattedTextGeburtstag = new javax.swing.JFormattedTextField();
        jLabelMitgliedsnummer1 = new javax.swing.JLabel();
        jFormattedTextGeburtstagVorschau = new javax.swing.JFormattedTextField();
        jTextLastDeletedID = new javax.swing.JTextField();
        jLabelLastDeletedID = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialogFehlerhafteIDEingabeLayout = new javax.swing.GroupLayout(jDialogFehlerhafteIDEingabe.getContentPane());
        jDialogFehlerhafteIDEingabe.getContentPane().setLayout(jDialogFehlerhafteIDEingabeLayout);
        jDialogFehlerhafteIDEingabeLayout.setHorizontalGroup(
            jDialogFehlerhafteIDEingabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogFehlerhafteIDEingabeLayout.setVerticalGroup(
            jDialogFehlerhafteIDEingabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mitgliederverwaltung Fitness-Studio");

        jLabelHauptprogramm.setText("Hauptprogramm");

        jButtonStartHauptprogramm.setText("Start");
        jButtonStartHauptprogramm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartHauptprogrammActionPerformed(evt);
            }
        });

        textMethodenNummer.setColumns(3);

        javax.swing.GroupLayout jPanelDemoAufKonsoleLayout = new javax.swing.GroupLayout(jPanelDemoAufKonsole);
        jPanelDemoAufKonsole.setLayout(jPanelDemoAufKonsoleLayout);
        jPanelDemoAufKonsoleLayout.setHorizontalGroup(
            jPanelDemoAufKonsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDemoAufKonsoleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHauptprogramm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStartHauptprogramm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMethodenNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        jPanelDemoAufKonsoleLayout.setVerticalGroup(
            jPanelDemoAufKonsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDemoAufKonsoleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDemoAufKonsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDemoAufKonsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonStartHauptprogramm)
                        .addComponent(textMethodenNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelHauptprogramm))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Demo auf Konsole", jPanelDemoAufKonsole);

        jListMitglieder.setModel(msmlm);
        jScrollPane1.setViewportView(jListMitglieder);

        javax.swing.GroupLayout jPanelMitglieder_ListenausgabeLayout = new javax.swing.GroupLayout(jPanelMitglieder_Listenausgabe);
        jPanelMitglieder_Listenausgabe.setLayout(jPanelMitglieder_ListenausgabeLayout);
        jPanelMitglieder_ListenausgabeLayout.setHorizontalGroup(
            jPanelMitglieder_ListenausgabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMitglieder_ListenausgabeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMitglieder_ListenausgabeLayout.setVerticalGroup(
            jPanelMitglieder_ListenausgabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMitglieder_ListenausgabeLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mitglieder: Listenausgabe", jPanelMitglieder_Listenausgabe);

        jTableMitglieder.setModel(mtm);
        jScrollPane2.setViewportView(jTableMitglieder);

        javax.swing.GroupLayout jPanelMitglieder_TabelleLayout = new javax.swing.GroupLayout(jPanelMitglieder_Tabelle);
        jPanelMitglieder_Tabelle.setLayout(jPanelMitglieder_TabelleLayout);
        jPanelMitglieder_TabelleLayout.setHorizontalGroup(
            jPanelMitglieder_TabelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMitglieder_TabelleLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanelMitglieder_TabelleLayout.setVerticalGroup(
            jPanelMitglieder_TabelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMitglieder_TabelleLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mitglieder: Tabelle", jPanelMitglieder_Tabelle);

        jLabelMitgliedsdatenUeberschrift.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMitgliedsdatenUeberschrift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMitgliedsdatenUeberschrift.setText("Vorschau");
        jLabelMitgliedsdatenUeberschrift.setPreferredSize(new java.awt.Dimension(69, 18));

        jLabelNachName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNachName.setText("Nachname");

        jLabelVorname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelVorname.setText("Vorname");

        jLabelPlz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPlz.setText("Postleitzahl");

        jLabelWohnort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelWohnort.setText("Wohnort");

        jLabelMitgliedsnummer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMitgliedsnummer.setText("Mitgliedsnummer");

        jTextNachname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNachnameFocusGained(evt);
            }
        });

        jTextVorname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextVornameFocusGained(evt);
            }
        });

        jTextPlz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPlzFocusGained(evt);
            }
        });

        jTextWohnort.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextWohnortFocusGained(evt);
            }
        });

        jLabelErrechneteMitgliedsnummer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jButtonMitgliedVorbereiten.setText("Mitglied vorbereiten");
        jButtonMitgliedVorbereiten.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonMitgliedVorbereiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMitgliedVorbereitenActionPerformed(evt);
            }
        });

        jLabelAlter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAlter.setText("Alter");

        jTextAlter.setEditable(false);

        jTextErrechneteMitgliedsnummer.setEditable(false);
        jTextErrechneteMitgliedsnummer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonMitgliedsdatenSpeichern.setText("Mitgliedsdaten speichern");
        jButtonMitgliedsdatenSpeichern.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonMitgliedsdatenSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMitgliedsdatenSpeichernActionPerformed(evt);
            }
        });

        jTextNachnameVorschau.setEditable(false);
        jTextNachnameVorschau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNachnameVorschauActionPerformed(evt);
            }
        });

        jTextVornameVorschau.setEditable(false);
        jTextVornameVorschau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVornameVorschauActionPerformed(evt);
            }
        });

        jTextPlzVorschau.setEditable(false);
        jTextPlzVorschau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPlzVorschauActionPerformed(evt);
            }
        });

        jTextWohnortVorschau.setEditable(false);
        jTextWohnortVorschau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextWohnortVorschauActionPerformed(evt);
            }
        });

        jTextAlterVorschau.setEditable(false);

        jLabelMitgliedsdatenUeberschrift1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMitgliedsdatenUeberschrift1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMitgliedsdatenUeberschrift1.setText("Mitgliedsdateneingabe");
        jLabelMitgliedsdatenUeberschrift1.setPreferredSize(new java.awt.Dimension(69, 18));

        jButtonDelete_ID.setText("Delete (ID)");
        jButtonDelete_ID.setActionCommand("jButtonDelete (ID)");
        jButtonDelete_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete_IDActionPerformed(evt);
            }
        });

        jTextDelete_ID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextDelete_ID.setText("0");
        jTextDelete_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextDelete_IDFocusGained(evt);
            }
        });
        jTextDelete_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDelete_IDActionPerformed(evt);
            }
        });

        jButtonMitgliedEditierbar.setText("Mitgliedsdaten bearbeiten");
        jButtonMitgliedEditierbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMitgliedEditierbarActionPerformed(evt);
            }
        });

        jFormattedTextGeburtstag.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFormattedTextGeburtstag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextGeburtstagActionPerformed(evt);
            }
        });

        jLabelMitgliedsnummer1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMitgliedsnummer1.setText("Geburtstag");

        jFormattedTextGeburtstagVorschau.setEditable(false);
        jFormattedTextGeburtstagVorschau.setToolTipText("");
        jFormattedTextGeburtstagVorschau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextGeburtstagVorschauActionPerformed(evt);
            }
        });

        jTextLastDeletedID.setEditable(false);
        jTextLastDeletedID.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextLastDeletedID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastDeletedIDActionPerformed(evt);
            }
        });

        jLabelLastDeletedID.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabelLastDeletedID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLastDeletedID.setText("Letzte gelöschte ID");

        javax.swing.GroupLayout jPanelStd_MitgliederVerwaltenLayout = new javax.swing.GroupLayout(jPanelStd_MitgliederVerwalten);
        jPanelStd_MitgliederVerwalten.setLayout(jPanelStd_MitgliederVerwaltenLayout);
        jPanelStd_MitgliederVerwaltenLayout.setHorizontalGroup(
            jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStd_MitgliederVerwaltenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelNachName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelVorname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPlz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelWohnort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMitgliedsnummer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMitgliedsnummer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMitgliedsdatenUeberschrift1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextErrechneteMitgliedsnummer)
                        .addComponent(jFormattedTextGeburtstag)
                        .addComponent(jTextWohnort)
                        .addComponent(jTextPlz)
                        .addComponent(jTextVorname)
                        .addComponent(jTextNachname)
                        .addGroup(jPanelStd_MitgliederVerwaltenLayout.createSequentialGroup()
                            .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextDelete_ID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonMitgliedEditierbar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextLastDeletedID)
                                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createSequentialGroup()
                                    .addComponent(jLabelLastDeletedID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addComponent(jTextAlter)))
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelErrechneteMitgliedsnummer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelStd_MitgliederVerwaltenLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMitgliedsdatenUeberschrift, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(jTextVornameVorschau)
                                    .addComponent(jTextPlzVorschau)
                                    .addComponent(jTextWohnortVorschau)
                                    .addComponent(jTextAlterVorschau)
                                    .addComponent(jFormattedTextGeburtstagVorschau)
                                    .addComponent(jTextNachnameVorschau))
                                .addComponent(jButtonMitgliedVorbereiten, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jButtonMitgliedsdatenSpeichern, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStd_MitgliederVerwaltenLayout.setVerticalGroup(
            jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStd_MitgliederVerwaltenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMitgliedsdatenUeberschrift, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMitgliedsdatenUeberschrift1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNachName)
                    .addComponent(jTextNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNachnameVorschau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVorname)
                    .addComponent(jTextVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextVornameVorschau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlz)
                    .addComponent(jTextPlz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPlzVorschau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWohnort)
                    .addComponent(jTextWohnort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextWohnortVorschau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMitgliedsnummer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextGeburtstag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextGeburtstagVorschau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMitgliedsnummer)
                        .addComponent(jTextErrechneteMitgliedsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelErrechneteMitgliedsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlter)
                    .addComponent(jTextAlter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAlterVorschau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMitgliedVorbereiten)
                    .addComponent(jButtonMitgliedEditierbar)
                    .addComponent(jLabelLastDeletedID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStd_MitgliederVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete_ID)
                    .addComponent(jTextDelete_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMitgliedsdatenSpeichern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextLastDeletedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Std-Mitglieder verwalten ", jPanelStd_MitgliederVerwalten);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartHauptprogrammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartHauptprogrammActionPerformed
        // TODO 
        final long start = System.currentTimeMillis();
        Timer timer = new Timer(500, null);
        timer.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                System.out.println("Das Programm läuft seit "
                        + (System.currentTimeMillis() - start) + " Millisekunden.");
            }
        });

        try {
            new Hauptprogramm().go((int) Integer.parseInt(textMethodenNummer.getText()));
        } catch (NumberFormatException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonStartHauptprogrammActionPerformed

    private void jButtonMitgliedEditierbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMitgliedEditierbarActionPerformed
        setAllJtextfeldTextEditableTrue(jTextfeldListe);
    }//GEN-LAST:event_jButtonMitgliedEditierbarActionPerformed

    private void jTextDelete_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDelete_IDActionPerformed
        jTextDelete_ID.selectAll();
    }//GEN-LAST:event_jTextDelete_IDActionPerformed

    private void jTextDelete_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDelete_IDFocusGained
        jTextDelete_ID.selectAll();
    }//GEN-LAST:event_jTextDelete_IDFocusGained

    private void jButtonDelete_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete_IDActionPerformed
        boolean EingabeSinnvoll = false;
        // boolsche Variable, um zu sehen, ob die Eingabe
        // syntaktisch sinvoll ist
        System.out.println("Boolsche Variable hat momentan den Wert: " + EingabeSinnvoll);
        try {
            int id = Integer.parseInt(jTextDelete_ID.getText());
            if (id >= 1) {
                EingabeSinnvoll = true;
                new FitnessStudioProjektStandardMitgliedDb().delete(id);
                jTextLastDeletedID.setText(jTextDelete_ID.getText());
                jTextDelete_ID.setText("");
            }
        } catch (NumberFormatException ex) {
            System.out.println("Fehlerhafte ID-Eingabe!");
        }
        if (!EingabeSinnvoll) {
            JOptionPane.showMessageDialog(jDialogFehlerhafteIDEingabe, "Ihre ID-"
                    + "Eingabe ist entweder \nSINNFREI oder FEHLERHAFT!",
                    "Eingabe-Fehler!!", JOptionPane.WARNING_MESSAGE);
            jTextDelete_ID.setText("0");
            jTextDelete_ID.requestFocus();
        }
    }//GEN-LAST:event_jButtonDelete_IDActionPerformed

    private void jButtonMitgliedsdatenSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMitgliedsdatenSpeichernActionPerformed
        if (mitgliedErzeugbar) {
            dummyVorname = jTextVorname.getText();
            dummyPlz = jTextPlz.getText();
            dummyWohnort = jTextWohnort.getText();

            StandardMitglied neuesStandardMitglied = new StandardMitglied(dummyNachname,
                    dummyVorname, dummyPlz, dummyWohnort,
                    new GregorianCalendar(dummyJahrDerGeburt, dummyMonatDerGeburt - 1,
                            dummyTagDerGeburt), fitnessstudio);
            fitnessstudio.addStandardMitglied(neuesStandardMitglied);
            FitnessStudioProjektStandardMitgliedDb test = new FitnessStudioProjektStandardMitgliedDb();
            test.insert(neuesStandardMitglied);
            fitnessstudio.anzeigeStandardMitglieder();
            clearAllMitgliedTabVisibleTextFields();
            clearAllMitgliedTabVisibleTextVorschauFields();
            setAllJtextfeldTextEditableTrue(jTextfeldListe);
        } else {
            System.out.println("Vervollständigen Sie Ihre Angaben und prüfen "
                    + "Sie ggf., ob der Eintrag im Feld \"Alter\" sinnvoll ist!");
            System.out.println("Tipp: Drücken Sie den \"Mitglied vorbereiten\""
                    + "-Button!");
        }
    }//GEN-LAST:event_jButtonMitgliedsdatenSpeichernActionPerformed

    private void jButtonMitgliedVorbereitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMitgliedVorbereitenActionPerformed
        mitgliedErzeugbar = true;
        dummyNachname = jTextNachname.getText();
        jFormattedTextGeburtstagVorschau.setText(jFormattedTextGeburtstag.getText());
        dummyGeburtstagsString = jFormattedTextGeburtstag.getText();
//        System.out.println(""+dummyGeburtstagsString);
        clearAllMitgliedTabVisibleTextVorschauFields();
        GregorianCalendar now = new GregorianCalendar();
        dummyAlter = -1;
        if (!dummyGeburtstagsString.isEmpty()) {
            dummyTagDerGeburt = (int) Integer.parseInt(dummyGeburtstagsString.substring(0, 2));

            dummyMonatDerGeburt = (int) Integer.parseInt(dummyGeburtstagsString.substring(3, 5));
            dummyJahrDerGeburt = (int) Integer.parseInt(dummyGeburtstagsString.substring(6, 10));
            dummyAlter = now.get(Calendar.YEAR) - dummyJahrDerGeburt;
        }
        if ((now.get(Calendar.MONTH) + 1 < dummyMonatDerGeburt)
                | ((now.get(Calendar.MONTH) + 1 == dummyMonatDerGeburt)
                & (now.get(Calendar.DAY_OF_MONTH) < dummyTagDerGeburt))) {
            dummyAlter += -1;
        }
        jTextAlter.setText("" + dummyAlter);

//        System.out.println("Aktuelles Datum: " + now.get(Calendar.YEAR) + "-" 
//                + now.get(Calendar.MONTH) + "-"
//                + now.get(Calendar.DAY_OF_MONTH));
 /*
         jTextfeldListe.set(0, jTextNachname);
         jTextfeldListe.set(1, jTextWohnort);
         jTextfeldListe.set(2, jTextPlz);
         jTextfeldListe.set(3, jTextWohnort);
         jTextfeldListe.remove(4);
         jTextfeldListe.add(jTextAlter);
         jTextfeldListe.add(1, jTextVorname);
         jTextfeldListe.remove(2);
         jTextfeldListe.remove(4);
         */
        setInitialWertejTextFeldListe();
        /*
         // Testausgabe
         for (int i = 0; i < jTextfeldListe.size(); i++) {
         System.out.println("jTextFeld " + i + ": "
         + (jTextfeldListe.get(i)).getText());
         }
         */
        // die folgende erweiterte for-Schleife hat Redundanzen entfernt; ihr Sinn
        // ist es, dass der User die fehlerhaften Eingaben von oben nach unten
        // abarbeiten kann: Ein String darf NICHT mit einem Leerzeichen anfangen
        // und die Eingabe des Alters soll eine Integerzahl >= 0 beinhalten
        for (JTextField jTextfeld : jTextfeldListe) {
            if (((jTextfeld.getText()).isEmpty())
                    || ((jTextfeld.getText()).indexOf(" ") == 0)) {
                getJtextfeldTextWithFocusRequest(jTextfeld);
                mitgliedErzeugbar = false;
                break;
            }
        }

        if (mitgliedErzeugbar) {
            try {
                dummyAlter = (int) Integer.parseInt(jTextAlter.getText());
                if (dummyAlter >= 0) {
                    StandardMitglied stdmgld = new StandardMitglied(dummyNachname,
                            dummyVorname, dummyPlz, dummyWohnort,
                            new GregorianCalendar(dummyJahrDerGeburt, dummyMonatDerGeburt - 1,
                                    dummyTagDerGeburt), fitnessstudio);
                    // Vorsicht: Hier nur Ausgabe, wie die Daten eines potentiellen
                    // neuen Standardmitglieds aussehen
                    jLabelErrechneteMitgliedsnummer.setText("" + stdmgld.getMitgliedNummer());
                    jTextErrechneteMitgliedsnummer.setText("" + stdmgld.getMitgliedNummer());
                    // für ein erzeugbares Mitglied sollen die bisher benutzten Eingabe nicht
                    // ohne das Verwenden eines Extra-Button wieder editierbar sein
                    setAllJtextfeldTextEditableFalse(jTextfeldListe);
                } else {
                    mitgliedErzeugbar = false;
                    jTextAlter.requestFocus();
                }
            } catch (NumberFormatException ex) {
                System.out.println("Fehler beim Konvertieren des Alters, Ihre "
                        + "merkwürdige Eingabe war: " + jTextAlter.getText() + " !");
                System.out.println("\n!!! Korrigieren Sie bitte Ihre Eingabe!!!\n");
                if (jTextAlter.getText().isEmpty()) {
                    jTextAlter.setText("" + dummyAlter);
                }
                jTextAlter.requestFocus();
                mitgliedErzeugbar = false;
            }
        }
        clearAllMitgliedTabVisibleTextVorschauFields();
    }//GEN-LAST:event_jButtonMitgliedVorbereitenActionPerformed

    private void jTextWohnortFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextWohnortFocusGained
        jTextWohnort.selectAll();
    }//GEN-LAST:event_jTextWohnortFocusGained

    private void jTextPlzFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPlzFocusGained
        jTextPlz.selectAll();
    }//GEN-LAST:event_jTextPlzFocusGained

    private void jTextVornameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextVornameFocusGained
        jTextVorname.selectAll();
    }//GEN-LAST:event_jTextVornameFocusGained

    private void jTextNachnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNachnameFocusGained
        jTextNachname.selectAll();
    }//GEN-LAST:event_jTextNachnameFocusGained

    private void jFormattedTextGeburtstagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextGeburtstagActionPerformed
        jFormattedTextGeburtstag.selectAll();
    }//GEN-LAST:event_jFormattedTextGeburtstagActionPerformed

    private void jFormattedTextGeburtstagVorschauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextGeburtstagVorschauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextGeburtstagVorschauActionPerformed

    private void jTextWohnortVorschauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextWohnortVorschauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextWohnortVorschauActionPerformed

    private void jTextPlzVorschauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPlzVorschauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPlzVorschauActionPerformed

    private void jTextNachnameVorschauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNachnameVorschauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNachnameVorschauActionPerformed

    private void jTextVornameVorschauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVornameVorschauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVornameVorschauActionPerformed

    private void jTextLastDeletedIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLastDeletedIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLastDeletedIDActionPerformed

    void clearAllMitgliedTabVisibleTextFields() {
        jTextNachname.setText("");
        jTextVorname.setText("");
        jTextPlz.setText("");
        jTextWohnort.setText("");
        jTextAlter.setText("");
        jTextErrechneteMitgliedsnummer.setText("");
        jLabelErrechneteMitgliedsnummer.setText("");
        //jFormattedTextGeburtstag.setText("01.01.1800");
        jFormattedTextGeburtstag.setText("");
        jTextDelete_ID.setText("");
    }

    void clearAllMitgliedTabVisibleTextVorschauFields() {
        jTextNachnameVorschau.setText(jTextNachname.getText());
        jTextVornameVorschau.setText(jTextVorname.getText());
        jTextPlzVorschau.setText(jTextPlz.getText());
        jTextWohnortVorschau.setText(jTextWohnort.getText());
        jTextAlterVorschau.setText(jTextAlter.getText());
        jFormattedTextGeburtstagVorschau.setText(
                jFormattedTextGeburtstag.getText());
    }

    private String getJtextfeldTextWithFocusRequest(JTextField jTextfeld) {
        jTextfeld.requestFocus();
        return jTextfeld.getText();
    }

    private void setAllJtextfeldTextEditableTrue(List<JTextField> jTextfeldListe) {
        for (JTextField jTextfeld : jTextfeldListe) {
            jTextfeld.setEditable(true);
        }
    }

    private void setAllJtextfeldTextEditableFalse(List<JTextField> jTextfeldListe) {
        for (JTextField jTextfeld : jTextfeldListe) {
            jTextfeld.setEditable(false);
        }
    }

    private void setInitialWertejTextFeldListe() {
        jTextfeldListe.add(jTextNachname);
        jTextfeldListe.add(jTextVorname);
        jTextfeldListe.add(jTextPlz);
        jTextfeldListe.add(jTextWohnort);
        jTextfeldListe.add(jFormattedTextGeburtstag);
        //jTextfeldListe.add(jTextAlter);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFitnessStudioVerwaltung.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFitnessStudioVerwaltung.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFitnessStudioVerwaltung.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFitnessStudioVerwaltung.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameFitnessStudioVerwaltung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete_ID;
    private javax.swing.JButton jButtonMitgliedEditierbar;
    private javax.swing.JButton jButtonMitgliedVorbereiten;
    private javax.swing.JButton jButtonMitgliedsdatenSpeichern;
    private javax.swing.JButton jButtonStartHauptprogramm;
    private javax.swing.JDialog jDialogFehlerhafteIDEingabe;
    private javax.swing.JFormattedTextField jFormattedTextGeburtstag;
    private javax.swing.JFormattedTextField jFormattedTextGeburtstagVorschau;
    private javax.swing.JLabel jLabelAlter;
    private javax.swing.JLabel jLabelErrechneteMitgliedsnummer;
    private javax.swing.JLabel jLabelHauptprogramm;
    private javax.swing.JLabel jLabelLastDeletedID;
    private javax.swing.JLabel jLabelMitgliedsdatenUeberschrift;
    private javax.swing.JLabel jLabelMitgliedsdatenUeberschrift1;
    private javax.swing.JLabel jLabelMitgliedsnummer;
    private javax.swing.JLabel jLabelMitgliedsnummer1;
    private javax.swing.JLabel jLabelNachName;
    private javax.swing.JLabel jLabelPlz;
    private javax.swing.JLabel jLabelVorname;
    private javax.swing.JLabel jLabelWohnort;
    private javax.swing.JList<String> jListMitglieder;
    private javax.swing.JPanel jPanelDemoAufKonsole;
    private javax.swing.JPanel jPanelMitglieder_Listenausgabe;
    private javax.swing.JPanel jPanelMitglieder_Tabelle;
    private javax.swing.JPanel jPanelStd_MitgliederVerwalten;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMitglieder;
    private javax.swing.JTextField jTextAlter;
    private javax.swing.JTextField jTextAlterVorschau;
    private javax.swing.JTextField jTextDelete_ID;
    private javax.swing.JTextField jTextErrechneteMitgliedsnummer;
    private javax.swing.JTextField jTextLastDeletedID;
    private javax.swing.JTextField jTextNachname;
    private javax.swing.JTextField jTextNachnameVorschau;
    private javax.swing.JTextField jTextPlz;
    private javax.swing.JTextField jTextPlzVorschau;
    private javax.swing.JTextField jTextVorname;
    private javax.swing.JTextField jTextVornameVorschau;
    private javax.swing.JTextField jTextWohnort;
    private javax.swing.JTextField jTextWohnortVorschau;
    private javax.swing.JTextField textMethodenNummer;
    // End of variables declaration//GEN-END:variables

}
